<MyGridLayout>
    GridLayout:
        cols:1

        Gridlayout:
            cols:2

            Label:
                text: "Name"
            TextInput:
                multiline:False

            Label:
                text: "Favorite Pizza"
            TextInput:
                multiline:False

            Label:
                text: "Favorite Color"
            TextInput:
                multiline:False
        Button:
            text: "Submit"
            